/**
 * Supabase Database type definitions.
 *
 * Generated by: supabase gen types typescript --local > packages/db/src/types.ts
 * (Manually maintained until Phase 2 migrations are applied locally with Docker.)
 *
 * To regenerate after `supabase db push`:
 *   supabase gen types typescript --local > packages/db/src/types.ts
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      credit_ledger: {
        Row: {
          created_at: string
          delta: number
          id: string
          note: string | null
          reason: Database['public']['Enums']['credit_reason']
          reference_id: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          delta: number
          id?: string
          note?: string | null
          reason: Database['public']['Enums']['credit_reason']
          reference_id?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          delta?: number
          id?: string
          note?: string | null
          reason?: Database['public']['Enums']['credit_reason']
          reference_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'credit_ledger_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
        ]
      }
      feedback: {
        Row: {
          cleanliness: Database['public']['Enums']['cleanliness']
          created_at: string
          id: string
          note: string | null
          user_id: string | null
          washroom_id: string
        }
        Insert: {
          cleanliness: Database['public']['Enums']['cleanliness']
          created_at?: string
          id?: string
          note?: string | null
          user_id?: string | null
          washroom_id: string
        }
        Update: {
          cleanliness?: Database['public']['Enums']['cleanliness']
          created_at?: string
          id?: string
          note?: string | null
          user_id?: string | null
          washroom_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'feedback_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'feedback_washroom_id_fkey'
            columns: ['washroom_id']
            isOneToOne: false
            referencedRelation: 'washrooms'
            referencedColumns: ['id']
          },
        ]
      }
      flags: {
        Row: {
          created_at: string
          id: string
          note: string | null
          reason: Database['public']['Enums']['flag_reason']
          resolved: boolean
          resolved_at: string | null
          resolved_by: string | null
          user_id: string | null
          washroom_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          note?: string | null
          reason: Database['public']['Enums']['flag_reason']
          resolved?: boolean
          resolved_at?: string | null
          resolved_by?: string | null
          user_id?: string | null
          washroom_id: string
        }
        Update: {
          created_at?: string
          id?: string
          note?: string | null
          reason?: Database['public']['Enums']['flag_reason']
          resolved?: boolean
          resolved_at?: string | null
          resolved_by?: string | null
          user_id?: string | null
          washroom_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'flags_resolved_by_fkey'
            columns: ['resolved_by']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'flags_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'flags_washroom_id_fkey'
            columns: ['washroom_id']
            isOneToOne: false
            referencedRelation: 'washrooms'
            referencedColumns: ['id']
          },
        ]
      }
      pins: {
        Row: {
          expires_at: string
          id: string
          pinned_at: string
          released_at: string | null
          user_id: string
          washroom_id: string
        }
        Insert: {
          expires_at?: string
          id?: string
          pinned_at?: string
          released_at?: string | null
          user_id: string
          washroom_id: string
        }
        Update: {
          expires_at?: string
          id?: string
          pinned_at?: string
          released_at?: string | null
          user_id?: string
          washroom_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'pins_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'pins_washroom_id_fkey'
            columns: ['washroom_id']
            isOneToOne: false
            referencedRelation: 'washrooms'
            referencedColumns: ['id']
          },
        ]
      }
      notification_queue: {
        Row: {
          created_at: string
          id: string
          sent: boolean
          type: Database['public']['Enums']['notification_type']
          user_id: string
          washroom_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          sent?: boolean
          type: Database['public']['Enums']['notification_type']
          user_id: string
          washroom_id: string
        }
        Update: {
          created_at?: string
          id?: string
          sent?: boolean
          type?: Database['public']['Enums']['notification_type']
          user_id?: string
          washroom_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'notification_queue_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'notification_queue_washroom_id_fkey'
            columns: ['washroom_id']
            isOneToOne: false
            referencedRelation: 'washrooms'
            referencedColumns: ['id']
          },
        ]
      }
      users: {
        Row: {
          anonymous_username: string
          auth_id: string
          created_at: string
          email: string | null
          id: string
          revenuecat_customer_id: string | null
          role: Database['public']['Enums']['user_role']
          subscription_expires_at: string | null
          tier: Database['public']['Enums']['user_tier']
          updated_at: string
        }
        Insert: {
          anonymous_username: string
          auth_id: string
          created_at?: string
          email?: string | null
          id?: string
          revenuecat_customer_id?: string | null
          role?: Database['public']['Enums']['user_role']
          subscription_expires_at?: string | null
          tier?: Database['public']['Enums']['user_tier']
          updated_at?: string
        }
        Update: {
          anonymous_username?: string
          auth_id?: string
          created_at?: string
          email?: string | null
          id?: string
          revenuecat_customer_id?: string | null
          role?: Database['public']['Enums']['user_role']
          subscription_expires_at?: string | null
          tier?: Database['public']['Enums']['user_tier']
          updated_at?: string
        }
        Relationships: []
      }
      verifications: {
        Row: {
          created_at: string
          id: string
          notes: string | null
          photo_url: string | null
          resolved_at: string | null
          status: Database['public']['Enums']['verification_status']
          submitter_id: string           // NOT NULL — the subscriber who submitted
          verifier_id: string | null
          washroom_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          notes?: string | null
          photo_url?: string | null
          resolved_at?: string | null
          status?: Database['public']['Enums']['verification_status']
          submitter_id: string           // required on insert
          verifier_id?: string | null
          washroom_id: string
        }
        Update: {
          created_at?: string
          id?: string
          notes?: string | null
          photo_url?: string | null
          resolved_at?: string | null
          status?: Database['public']['Enums']['verification_status']
          submitter_id?: string
          verifier_id?: string | null
          washroom_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'verifications_submitter_id_fkey'
            columns: ['submitter_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'verifications_verifier_id_fkey'
            columns: ['verifier_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'verifications_washroom_id_fkey'
            columns: ['washroom_id']
            isOneToOne: false
            referencedRelation: 'washrooms'
            referencedColumns: ['id']
          },
        ]
      }
      washrooms: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          is_pay_to_use: boolean
          last_cleanliness: Database['public']['Enums']['cleanliness'] | null
          lat: number
          lng: number
          name: string
          status: Database['public']['Enums']['washroom_status']
          type: Database['public']['Enums']['washroom_type']
          updated_at: string
          verified: boolean
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          is_pay_to_use?: boolean
          last_cleanliness?: Database['public']['Enums']['cleanliness'] | null
          lat: number
          lng: number
          name: string
          status?: Database['public']['Enums']['washroom_status']
          type: Database['public']['Enums']['washroom_type']
          updated_at?: string
          verified?: boolean
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          is_pay_to_use?: boolean
          last_cleanliness?: Database['public']['Enums']['cleanliness'] | null
          lat?: number
          lng?: number
          name?: string
          status?: Database['public']['Enums']['washroom_status']
          type?: Database['public']['Enums']['washroom_type']
          updated_at?: string
          verified?: boolean
        }
        Relationships: [
          {
            foreignKeyName: 'washrooms_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: {
      user_credit_balances: {
        Row: {
          credits: number | null
          user_id: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      get_tier: {
        Args: Record<PropertyKey, never>
        Returns: string
      }
      get_user_credit_balance: {
        Args: {
          p_user_id: string
        }
        Returns: number
      }
      get_user_id: {
        Args: Record<PropertyKey, never>
        Returns: string
      }
      is_admin: {
        Args: Record<PropertyKey, never>
        Returns: boolean
      }
    }
    Enums: {
      cleanliness: 'clean' | 'dirty'
      credit_reason:
        | 'washroom_verified'
        | 'subscription_renewal'
        | 'subscription_partial'
        | 'manual_admin_adjust'
        | 'bonus'
      flag_reason:
        | 'closed_permanently'
        | 'doesnt_exist'
        | 'incorrect_info'
        | 'inappropriate'
      notification_type: 'pin_expiring_soon' | 'verification_needed'
      user_role: 'user' | 'admin'
      user_tier: 'free' | 'subscriber'
      verification_status: 'pending' | 'approved' | 'rejected'
      washroom_status:
        | 'open'
        | 'pinned'
        | 'occupied'
        | 'closed'
        | 'pending_verification'
      washroom_type:
        | 'starbucks'
        | 'mcdonalds'
        | 'canadian_tire'
        | 'portable'
        | 'public'
        | 'other'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DefaultSchema = Database[Extract<keyof Database, 'public'>]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof (Database[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        Database[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? (Database[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      Database[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] &
        DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] &
        DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema['Enums']
    | { schema: keyof Database },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof Database },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof Database }
  ? Database[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never
