/**
 * lib/database.types.ts
 *
 * Auto-generated by Supabase CLI. Do not edit manually.
 * Regenerate with: supabase gen types typescript --linked > apps/admin/lib/database.types.ts
 *
 * Stub version — replace with generated output after running migrations.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type WashroomStatus = 'open' | 'pinned' | 'occupied' | 'closed' | 'pending_verification'
export type WashroomType = 'starbucks' | 'mcdonalds' | 'canadian_tire' | 'portable' | 'public' | 'other'
export type UserTier = 'free' | 'subscriber'
export type UserRole = 'user' | 'admin'
export type FlagReason = 'closed_permanently' | 'doesnt_exist' | 'incorrect_info' | 'inappropriate'
export type VerificationStatus = 'pending' | 'approved' | 'rejected'
export type CreditReason = 'washroom_verified' | 'subscription_renewal' | 'subscription_partial' | 'manual_admin_adjust' | 'bonus'

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          auth_id: string
          anonymous_username: string
          email: string | null
          role: UserRole
          tier: UserTier
          subscription_expires_at: string | null
          revenuecat_customer_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['users']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['users']['Insert']>
      }
      washrooms: {
        Row: {
          id: string
          name: string
          type: WashroomType
          lat: number
          lng: number
          is_pay_to_use: boolean
          status: WashroomStatus
          last_cleanliness: 'clean' | 'dirty' | null
          verified: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['washrooms']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['washrooms']['Insert']>
      }
      flags: {
        Row: {
          id: string
          washroom_id: string
          user_id: string | null
          reason: FlagReason
          note: string | null
          resolved: boolean
          resolved_by: string | null
          resolved_at: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['flags']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['flags']['Insert']>
      }
      verifications: {
        Row: {
          id: string
          washroom_id: string
          submitter_id: string
          verifier_id: string | null
          status: VerificationStatus
          notes: string | null
          photo_url: string | null
          created_at: string
          resolved_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['verifications']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['verifications']['Insert']>
      }
      credit_ledger: {
        Row: {
          id: string
          user_id: string
          delta: number
          reason: CreditReason
          reference_id: string | null
          note: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['credit_ledger']['Row'], 'id' | 'created_at'>
        Update: never // append-only
      }
    }
    Views: {
      user_credit_balances: {
        Row: { user_id: string; credits: number }
      }
    }
    Functions: {}
    Enums: {}
  }
}
